name: android

# build on c/cpp changes or workflow changes
on:
  push:
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'android/**'
      - '.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gettext openjdk-11-jdk-headless
    - name: Pull KetchupLand submodule
      run: |
        git submodule init
        git submodule update
    - name: Build with Gradle
      run: cd android; ./gradlew assemblerelease
    - name: Save armeabi artifact
      uses: actions/upload-artifact@v2
      with:
        name: KetchupLand-armeabi-v7a.apk
        path: android/app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk
    - name: Save arm64 artifact
      uses: actions/upload-artifact@v2
      with:
        name: KetchupLand-arm64-v8a.apk
        path: android/app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk
